// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResidenciasNLayer.Infrastructure.Data;

#nullable disable

namespace ResidenciasNLayer.Infrastructure.Migrations
{
    [DbContext(typeof(ResidenciasDbContext))]
    [Migration("20250910192125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("ResidentId", "OccurredAt");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Exit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDepartureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualReturnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExitStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("ExitTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("PlannedDepartureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedReturnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExitStatusId");

                    b.HasIndex("ExitTypeId");

                    b.HasIndex("ResidentId");

                    b.ToTable("exit", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExitId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("ExitId", "Action");

                    b.ToTable("exitauthorization", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("exitstatus", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("exittype", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Guard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("guard", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExitId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExitId");

                    b.HasIndex("Type");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Preceptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PreceptorTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreceptorTypeId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("preceptor", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.PreceptorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("preceptortype", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResidentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResidentTypeId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("\"StudentId\" IS NOT NULL");

                    b.HasIndex("TutorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("resident", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ResidentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("residenttype", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("shift", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tutor", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PushToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.Resident", "Resident")
                        .WithMany("Attendances")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Exit", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.ExitStatus", "ExitStatus")
                        .WithMany("Exits")
                        .HasForeignKey("ExitStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.ExitType", "ExitType")
                        .WithMany("Exits")
                        .HasForeignKey("ExitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.Resident", "Resident")
                        .WithMany("Exits")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExitStatus");

                    b.Navigation("ExitType");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitAuthorization", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.Exit", "Exit")
                        .WithMany("Authorizations")
                        .HasForeignKey("ExitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "PerformedByUser")
                        .WithMany("ExitAuthorizations")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exit");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Guard", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.Shift", "Shift")
                        .WithMany("Guards")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "User")
                        .WithOne("Guard")
                        .HasForeignKey("ResidenciasNLayer.Domain.Entities.Guard", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.Exit", "Exit")
                        .WithMany("Notifications")
                        .HasForeignKey("ExitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Preceptor", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.PreceptorType", "PreceptorType")
                        .WithMany("Preceptors")
                        .HasForeignKey("PreceptorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.Shift", "Shift")
                        .WithMany("Preceptors")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "User")
                        .WithOne("Preceptor")
                        .HasForeignKey("ResidenciasNLayer.Domain.Entities.Preceptor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreceptorType");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Resident", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.ResidentType", "ResidentType")
                        .WithMany("Residents")
                        .HasForeignKey("ResidentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Residents")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "User")
                        .WithOne("Resident")
                        .HasForeignKey("ResidenciasNLayer.Domain.Entities.Resident", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentType");

                    b.Navigation("Tutor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Tutor", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("ResidenciasNLayer.Domain.Entities.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.User", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Exit", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitStatus", b =>
                {
                    b.Navigation("Exits");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitType", b =>
                {
                    b.Navigation("Exits");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.PreceptorType", b =>
                {
                    b.Navigation("Preceptors");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Resident", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Exits");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ResidentType", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Shift", b =>
                {
                    b.Navigation("Guards");

                    b.Navigation("Preceptors");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.User", b =>
                {
                    b.Navigation("ExitAuthorizations");

                    b.Navigation("Guard");

                    b.Navigation("Notifications");

                    b.Navigation("Preceptor");

                    b.Navigation("Resident");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
