// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResidenciasNLayer.Infrastructure.Data;

#nullable disable

namespace ResidenciasNLayer.Infrastructure.Migrations
{
    [DbContext(typeof(ResidenciasDbContext))]
    [Migration("20250910181836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("event_id")
                        .HasColumnType("integer");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("event_id");

                    b.HasIndex("resident_id");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.device", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("tokenfcm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.exitrequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool?>("authorized_preceptor")
                        .HasColumnType("boolean");

                    b.Property<bool?>("authorized_tutor")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("departure_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("guard_exit_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("guard_return_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("return_eta_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("resident_id");

                    b.ToTable("exitrequest", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.guard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("shift_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("shift_id");

                    b.HasIndex("user_id");

                    b.ToTable("guard", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.novelty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("resident_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("resident_id");

                    b.ToTable("novelty", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.preceptor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("preceptortype_id")
                        .HasColumnType("integer");

                    b.Property<int>("shift_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("preceptortype_id");

                    b.HasIndex("shift_id");

                    b.HasIndex("user_id");

                    b.ToTable("preceptor", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.preceptortype", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("preceptortype", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.resident", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("residenttype_id")
                        .HasColumnType("integer");

                    b.Property<int>("tutor_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("residenttype_id");

                    b.HasIndex("tutor_id");

                    b.HasIndex("user_id");

                    b.ToTable("resident", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.residenttype", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("residenttype", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.shift", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<TimeOnly>("endtime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("starttime")
                        .HasColumnType("time without time zone");

                    b.HasKey("id");

                    b.ToTable("shift", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.tutor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("tutor", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.usertoken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("issued_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("usertoken", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.attendance", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.event", "event")
                        .WithMany()
                        .HasForeignKey("event_id");

                    b.HasOne("ResidenciasNLayer.Core.Entities.resident", "resident")
                        .WithMany()
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("event");

                    b.Navigation("resident");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.device", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.exitrequest", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.resident", "resident")
                        .WithMany()
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.guard", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.shift", "shift")
                        .WithMany()
                        .HasForeignKey("shift_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Core.Entities.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shift");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.novelty", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.resident", "resident")
                        .WithMany()
                        .HasForeignKey("resident_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.preceptor", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.preceptortype", "preceptortype")
                        .WithMany()
                        .HasForeignKey("preceptortype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Core.Entities.shift", "shift")
                        .WithMany()
                        .HasForeignKey("shift_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Core.Entities.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("preceptortype");

                    b.Navigation("shift");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.resident", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.residenttype", "residenttype")
                        .WithMany()
                        .HasForeignKey("residenttype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Core.Entities.tutor", "tutor")
                        .WithMany()
                        .HasForeignKey("tutor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Core.Entities.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("residenttype");

                    b.Navigation("tutor");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.tutor", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ResidenciasNLayer.Core.Entities.usertoken", b =>
                {
                    b.HasOne("ResidenciasNLayer.Core.Entities.user", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
