// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResidenciasNLayer.Infrastructure.Data;

#nullable disable

namespace ResidenciasNLayer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250910182719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("date_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_at");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("id");

                    b.HasIndex("created_by");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("approvedby")
                        .HasColumnType("text")
                        .HasColumnName("approvedby");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("exitdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exitdate");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("requestdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestdate");

                    b.Property<int>("residentid")
                        .HasColumnType("integer")
                        .HasColumnName("residentid");

                    b.Property<DateTime?>("returndate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returndate");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("tutorid")
                        .HasColumnType("integer")
                        .HasColumnName("tutorid");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("id");

                    b.HasIndex("residentid");

                    b.HasIndex("tutorid");

                    b.ToTable("exitrequest", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("expotoken")
                        .HasColumnType("TEXT")
                        .HasColumnName("expotoken");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.UserToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("expiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("usertoken", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.Event", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "createdby")
                        .WithMany("events")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("createdby");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.ExitRequest", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "resident")
                        .WithMany("exitrequests")
                        .HasForeignKey("residentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "tutor")
                        .WithMany()
                        .HasForeignKey("tutorid");

                    b.Navigation("resident");

                    b.Navigation("tutor");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("ResidenciasNLayer.Domain.Entities.User", "user")
                        .WithMany("usertokens")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ResidenciasNLayer.Domain.Entities.User", b =>
                {
                    b.Navigation("events");

                    b.Navigation("exitrequests");

                    b.Navigation("usertokens");
                });
#pragma warning restore 612, 618
        }
    }
}
