<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ResidenciasNLayer.Entities\ResidenciasNLayer.Entities.csproj" />
    <ProjectReference Include="..\ResidenciasNLayer.Data\ResidenciasNLayer.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
