// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResidenciasNLayer.Data;

#nullable disable

namespace ResidenciasNLayer.Api.Migrations
{
    [DbContext(typeof(ResidenciasDbContext))]
    [Migration("20250910183551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResidenciasNLayer.Entities.Device", b =>
                {
                    b.Property<string>("deviceid")
                        .HasColumnType("text")
                        .HasColumnName("deviceid");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("tokenfcm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tokenfcm");

                    b.HasKey("deviceid");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Entities.User", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userid"));

                    b.Property<string>("deviceid")
                        .HasColumnType("text")
                        .HasColumnName("deviceid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("userid");

                    b.HasIndex("deviceid")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ResidenciasNLayer.Entities.User", b =>
                {
                    b.HasOne("ResidenciasNLayer.Entities.Device", "Device")
                        .WithOne("User")
                        .HasForeignKey("ResidenciasNLayer.Entities.User", "deviceid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ResidenciasNLayer.Entities.Device", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
